### PR TITLE
Make clone of article

### PR DESCRIPTION
**Pull request by ammarkandel**
In this project, we used: 
- HTML
- flexbox 
- CSS grid 
- Float 
- Embedding images and videos to clone a New York Times article page.

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: 

**Hi @ammarkandel  AND @Nasa28**
Your commit messages are perfect :clap: However there is a problem with your README file and Pull Request. You have headings **Like Prerequisites, Setup, Install, Usage, Run tests, Deployment** in the README file without description. Please add the description according to headings, add a description in Pull Request and **Live link** in the README file.
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @ammarkandel and @Nasa28  !
### You have done well so far :clap: However, there are changes required for you to make for your project to be approved. Kindly work on them and submit them for another code review.

**Recommended**

 - [x] The font-family used throughout the project differs from that in the actual project.
Yours is `font-family: Times New Roman;`, it should be `nyt-franklin, helvetica, arial, sans-serif`.

- [x] The NYT logo should be smaller compared to what you currently have.

- [x] Adjust the navbar to look as similar as possible to the actual site's. Fix the buttons and add the horizontal line.

**Original**

Screenshot (32)


**Yours**

Screenshot (31)

 
- [x] The article's title uses a different font-family from that of the actual site, please get it to look as similar as possible to the actual site. Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to help.

- [x] The figcaption underneath the main image should be aligned to the image.

  **Original**

Screenshot (16)

**Yours**

Screenshot (33)

- [x] The social media row should be similar to that of the actual sites.

**Original**

Screenshot (17)

**Yours**

Screenshot (34)

- [x] Adjust the "Theory of Inflation" section to look as similar as possible to the actual site. The image is bigger than the actual site's and the font used is different as well.

- [ ] Fix the "More in Astronomy" and the section above it.

**Original**

Screenshot (22)
 
**Yours**

Screenshot (35)


- [ ] Fix the footer section as well.

**Original**

Screenshot (23)

**Yours**

Screenshot (36)


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello team :wave: 
You are almost there now, just a few more changes to be made.
- [x] Update the font family to the one used in the original website so that your clone will look as close as possible to the original.
- [x] Fix horizontal scroll and add the part shown in the screenshot to your project as it is missing in your clone.
Screenshot from 2020-11-27 19-21-35
Request another review once you are done making the changes 

slack(@ebeagusamuel)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @ammarkandel and @Nasa28 ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
